### ISSUE TITLE
using non-binary observations

### ISSUE THREAD

**Issue by psecekartal** [psolymos/ResourceSelection#17]
hello, we would like to use your package to calculate hoslem values however currently it only accepts binary observations as input but our data is non-binary, continuous. Is there a way to use it?

**Comment by psolymos** [comment]
Hi @psecekartal [H-L test](https://en.wikipedia.org/wiki/Hosmer%E2%80%93Lemeshow_test) is for binary outcomes, am not aware of a continuous version. Can you point me to the literature? You might want to try other goodness-of-fit metrics for continuous data.

**Comment by psecekartal** [comment]
Thank you for your reply, yes it was my bad, I was using event_time instead of event info!

**Comment by psolymos** [comment]
No problem! All the best.
