### ISSUE TITLE
Hosmer-Lemeshow test in GLMM (binomial family)

### ISSUE THREAD

**Issue by CamilaDeu** [psolymos/ResourceSelection#19]
Hi, I ran a GLMM (binomial family) using the lme4 package, and wanted to know if it is appropriate to apply the Hosmer-Lemeshow test to evaluate the model fit. Thank you!

library(lme4)

#GLMM
m1 <- glmer(Canto ~ T + H + Patm + V + Pp + CU + (1|Evento), data = Datos, family = binomial)

**Comment by psolymos** [comment]
Hi @CamilaDeu, using the Hosmer-Lemeshow with Binomial GLMM is more likely not applicable the same way as for GLMs. Hope this helps.
